name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: logging into az
        uses: azure/login@v3
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - name: Run command on VM
        run: |
          az account show 
