name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      
      - name: creating file in conatiner
        uses: azure/login@v3
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
         azcliversion: latest
         inlineScript: |
            az account show
            az vm ssh --resource-group sahani-ka-group --name sahani-ka-machine
            mkdir sahani
